# **Loading the dataset**

In [1]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.2.25)

In [2]:
import kagglehub

path = kagglehub.dataset_download("gabrielramos87/an-online-shop-business")

print(path)

Downloading to /root/.cache/kagglehub/datasets/gabrielramos87/an-online-shop-business/7.archive...

100%|██████████| 6.66M/6.66M [00:00<00:00, 111MB/s]

Extracting files...

/root/.cache/kagglehub/datasets/gabrielramos87/an-online-shop-business/versions/7

In [3]:
import os

os.listdir(path)

['Sales Transaction v.4a.csv']

In [4]:
import pandas as pd

df = pd.read_csv(f"{path}/Sales Transaction v.4a.csv")
df.head()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
0,581482,12/9/2019,22485,Set Of 2 Wooden Market Crates,21.47,12,17490.0,United Kingdom
1,581475,12/9/2019,22596,Christmas Star Wish List Chalkboard,10.65,36,13069.0,United Kingdom
2,581475,12/9/2019,23235,Storage Tin Vintage Leaf,11.53,12,13069.0,United Kingdom
3,581475,12/9/2019,23272,Tree T-Light Holder Willie Winkie,10.65,12,13069.0,United Kingdom
4,581475,12/9/2019,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6,13069.0,United Kingdom

In [7]:
df.tail()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
536345,C536548,12/1/2018,22168,Organiser Wood Antique White,18.96,-2,12472.0,Germany
536346,C536548,12/1/2018,21218,Red Spotty Biscuit Tin,14.09,-3,12472.0,Germany
536347,C536548,12/1/2018,20957,Porcelain Hanging Bell Small,11.74,-1,12472.0,Germany
536348,C536548,12/1/2018,22580,Advent Calendar Gingham Sack,16.35,-4,12472.0,Germany
536349,C536548,12/1/2018,22767,Triple Photo Frame Cornice,20.45,-2,12472.0,Germany

# **Inspections**

## Basic overview

In [8]:
df.shape

(536350, 8)

In [9]:
df.columns

Index(['TransactionNo', 'Date', 'ProductNo', 'ProductName', 'Price',
       'Quantity', 'CustomerNo', 'Country'],
      dtype='object')

## Data types & missing values

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536350 entries, 0 to 536349
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionNo  536350 non-null  object
 1   Date           536350 non-null  object
 2   ProductNo      536350 non-null  object
 3   ProductName    536350 non-null  object
 4   Price          536350 non-null  float64
 5   Quantity       536350 non-null  int64
 6   CustomerNo     536295 non-null  float64
 7   Country        536350 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 32.7+ MB

In [11]:
df.isnull().sum()

TransactionNo     0
Date              0
ProductNo         0
ProductName       0
Price             0
Quantity          0
CustomerNo       55
Country           0
dtype: int64

## Stats summary

In [12]:
df.describe()

               Price       Quantity     CustomerNo
count  536350.000000  536350.000000  536295.000000
mean       12.662182       9.919347   15227.893178
std         8.490450     216.662300    1716.582932
min         5.130000  -80995.000000   12004.000000
25%        10.990000       1.000000   13807.000000
50%        11.940000       3.000000   15152.000000
75%        14.090000      10.000000   16729.000000
max       660.620000   80995.000000   18287.000000

## Unique count

In [13]:
df.nunique()

TransactionNo    23204
Date               305
ProductNo         3768
ProductName       3768
Price              530
Quantity           510
CustomerNo        4738
Country             38
dtype: int64

## potential issues

In [17]:
# Checking for negative quantities
df[df['Quantity'] < 0]

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
1616,C581484,12/9/2019,23843,Paper Craft Little Birdie,6.19,-80995,16446.0,United Kingdom
1617,C581490,12/9/2019,22178,Victorian Glass Hanging T-Light,6.19,-12,14397.0,United Kingdom
1618,C581490,12/9/2019,23144,Zinc T-Light Holder Stars Small,6.04,-11,14397.0,United Kingdom
1619,C581568,12/9/2019,21258,Victorian Sewing Box Large,6.19,-5,15311.0,United Kingdom
1620,C581569,12/9/2019,84978,Hanging Heart Jar T-Light Holder,6.19,-1,17315.0,United Kingdom
...,...,...,...,...,...,...,...,...
536345,C536548,12/1/2018,22168,Organiser Wood Antique White,18.96,-2,12472.0,Germany
536346,C536548,12/1/2018,21218,Red Spotty Biscuit Tin,14.09,-3,12472.0,Germany
536347,C536548,12/1/2018,20957,Porcelain Hanging Bell Small,11.74,-1,12472.0,Germany
536348,C536548,12/1/2018,22580,Advent Calendar Gingham Sack,16.35,-4,12472.0,Germany
536349,C536548,12/1/2018,22767,Triple Photo Frame Cornice,20.45,-2,12472.0,Germany

In [18]:
#Negative prices
df[df['Price'] <= 0]

Empty DataFrame
Columns: [TransactionNo, Date, ProductNo, ProductName, Price, Quantity, CustomerNo, Country]
Index: []

In [22]:
# Missing customer
df[df['CustomerNo'].isnull()]

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
6511,C581406,12/8/2019,46000M,Polyester Filler Pad 45x45cm,6.19,-240,NaN,United Kingdom
6512,C581406,12/8/2019,46000S,Polyester Filler Pad 40x40cm,6.19,-300,NaN,United Kingdom
90098,C575153,11/8/2019,22947,Wooden Advent Calendar Red,44.25,-1,NaN,United Kingdom
102671,C574288,11/3/2019,22178,Victorian Glass Hanging T-Light,25.37,-1,NaN,United Kingdom
117263,C573180,10/28/2019,23048,Set Of 10 Lanterns Fairy Light Star,14.50,-1,NaN,United Kingdom
163160,C569495,10/4/2019,21843,Red Retrospot Cake Stand,21.47,-1,NaN,United Kingdom
190598,C567518,9/20/2019,22846,Bread Bin Diner Style Red,27.62,-1,NaN,United Kingdom
192284,C567518,9/20/2019,21871,Save The Planet Mug,11.94,-12,NaN,United Kingdom
242406,C563015,8/11/2019,46000M,Polyester Filler Pad 45x45cm,10.25,-160,NaN,United Kingdom
242407,C563015,8/11/2019,46000S,Polyester Filler Pad 40x40cm,10.25,-220,NaN,United Kingdom
246334,C562617,8/8/2019,23243,Set Of Tea Coffee Sugar Tins Pantry,15.32,-2,NaN,United Kingdom
254250,C561966,8/1/2019,22371,Airline Bag Vintage Tokyo 78,14.48,-1,NaN,United Kingdom
254254,C562030,8/1/2019,84595E,Large Tortilla Design Red Bowl,13.62,-1,NaN,United Kingdom
260633,C561239,7/26/2019,22427,Enamel Flower Jug Cream,16.35,-1,NaN,United Kingdom
260634,C561239,7/26/2019,22426,Enamel Wash Bowl Cream,14.09,-1,NaN,United Kingdom
260635,C561239,7/26/2019,84755,Colour Glass T-Light Holder Hanging,10.92,-4,NaN,United Kingdom
276396,C559949,7/14/2019,22699,Roses Regency Teacup And Saucer,13.27,-2,NaN,United Kingdom
285494,C559296,7/7/2019,23001,Travel Card Wallet Dotcomgiftshop,10.25,-200,NaN,United Kingdom
285495,C559296,7/7/2019,22616,Pack Of 12 London Tissues,10.25,-204,NaN,United Kingdom
285496,C559296,7/7/2019,23298,Spotty Bunting,10.25,-170,NaN,United Kingdom
297259,C558364,6/28/2019,22960,Jam Making Set With Jars,18.75,-1,NaN,United Kingdom
298352,558245,6/27/2019,22734,Set Of 6 Ribbons Vintage Christmas,10.25,8,NaN,United Kingdom
303165,C557664,6/21/2019,22847,Bread Bin Diner Style Ivory,25.57,-1,NaN,United Kingdom
304635,C557664,6/21/2019,23183,Mother's Kitchen Spoon Rest,14.09,-1,NaN,United Kingdom
311943,C556939,6/15/2019,46000M,Polyester Filler Pad 45x45cm,10.25,-80,NaN,United Kingdom
311944,C556939,6/15/2019,46000S,Polyester Filler Pad 40x40cm,10.25,-160,NaN,United Kingdom
333735,C554716,5/26/2019,22662,Lunch Bag Dolly Girl Design,5.97,-1,NaN,United Kingdom
333736,C554716,5/26/2019,23206,Lunch Bag Apple Design,5.97,-1,NaN,United Kingdom
342908,C553862,5/19/2019,84945,Multi Colour Silver T-Light Holder,21.28,-1,NaN,United Kingdom
342953,C553854,5/19/2019,22053,Empire Design Rosette,11.53,-1,NaN,United Kingdom
342954,C553854,5/19/2019,21703,Bag 125g Swirly Marbles,10.68,-1,NaN,United Kingdom
342955,C553854,5/19/2019,22891,Tea For One Polkadot,14.61,-1,NaN,United Kingdom
361482,C552230,5/6/2019,20735,Black Mini Tape Measure,10.25,-1,NaN,United Kingdom
361483,C552230,5/6/2019,22617,Baking Set Spaceboy Design,10.25,-1,NaN,United Kingdom
361484,C552230,5/6/2019,37327,Asstd Multicolour Circles Mug,10.25,-1,NaN,United Kingdom
361485,C552230,5/6/2019,84375,Set Of 20 Kids Cookie Cutters,10.25,-1,NaN,United Kingdom
361486,C552230,5/6/2019,84969,Box Of 6 Assorted Colour Teaspoons,10.25,-1,NaN,United Kingdom
395771,C548605,4/1/2019,22453,Measuring Tape Babushka Blue,13.27,-1,NaN,United Kingdom
412419,C547091,3/20/2019,22766,Photo Frame Cornice,13.27,-12,NaN,United Kingdom
412420,C547091,3/20/2019,21316,Small Chunky Glass Roman Bowl,13.27,-1,NaN,United Kingdom
412421,C547091,3/20/2019,22800,Antique Tall Swirlglass Trinket Pot,14.09,-4,NaN,United Kingdom
413780,C547008,3/18/2019,22567,20 Dolly Pegs Retrospot,11.53,-1,NaN,United Kingdom
416704,C546758,3/16/2019,22212,Four Hook White Lovebirds,12.40,-1,NaN,United Kingdom
429733,C545506,3/3/2019,22907,Pack Of 20 Napkins Pantry Design,11.12,-12,NaN,United Kingdom
454036,C543384,2/7/2019,48173C,Doormat Black Flock,18.40,-1,NaN,United Kingdom
455511,C543185,2/4/2019,22333,Retrospot Party Bag + Sticker Set,11.94,-14,NaN,United Kingdom
455512,C543185,2/4/2019,22332,Skulls Party Bag + Sticker Set,11.94,-14,NaN,United Kingdom
459432,C542860,2/1/2019,22580,Advent Calendar Gingham Sack,16.35,-1,NaN,United Kingdom
462607,C542540,1/28/2019,21658,Glass Beurre Dish,18.75,-1,NaN,United Kingdom
483197,C540854,1/12/2019,22461,Savoy Art Deco Clock,23.32,-1,NaN,United Kingdom
486650,C540559,1/10/2019,21888,Bingo Set,14.09,-4,NaN,United Kingdom
493036,C540155,1/5/2019,72802B,Ocean Scent Candle In Jewelled Box,14.16,-54,NaN,United Kingdom
495203,C539948,12/23/2018,21888,Bingo Set,14.09,-4,NaN,United Kingdom
497059,C539756,12/21/2018,22720,Set Of 3 Cake Tins Pantry Design,15.32,-1,NaN,United Kingdom
507547,C538686,12/14/2018,22467,Gumball Coat Rack,12.86,-1,NaN,United Kingdom

## Top products

In [24]:
df['ProductName'].value_counts().head(15)

ProductName
Cream Hanging Heart T-Light Holder    2378
Regency Cakestand 3 Tier              2200
Jumbo Bag Red Retrospot               2159
Party Bunting                         1727
Lunch Bag Red Retrospot               1639
Assorted Colour Bird Ornament         1501
Popcorn Holder                        1476
Set Of 3 Cake Tins Pantry Design      1473
Pack Of 72 Retrospot Cake Cases       1385
Lunch Bag Black Skull                 1350
Lunch Bag Suki Design                 1348
Natural Slate Heart Chalkboard        1280
Jumbo Bag Vintage Doily               1266
Jumbo Bag Pink Polkadot               1251
Heart Of Wicker Small                 1237
Name: count, dtype: int64

## sanity checks

In [25]:
df.duplicated().sum()

np.int64(5200)

In [26]:
# date range
df['Date'].min(), df['Date'].max()

('1/10/2019', '9/9/2019')